feat: ナビゲーションのコミュニティに処罰一覧を追加
jaoafa/jaoweb pull request #118
Opened 2021-10-14 18:30 UTC by book000

各ページの上部に表示されるナビゲーションの「コミュニティ」に bans.jaoafa.com へのリンク「処罰一覧」を追加しました。

2021-10-14 22:31 UTC, Hiratake commented
サーバでBANしたユーザの情報だから、コミュニティよりサーバ情報のほうがいいかねえ
処罰一覧ページでユーザ同士がコミュニケーションを取るとかなさげだし

2021-10-14 22:34 UTC, Hiratake requested changes

2021-10-14 22:34 UTC, Hiratake commented on components/TheHeader.vue
> +              value: 'community-bans',
サーバでBANしたユーザの情報だから、コミュニティよりサーバ情報のほうがいいかねえ
処罰一覧ページでユーザ同士がコミュニケーションを取るとかなさげだし

2021-10-15 04:30 UTC, book000 commented on components/TheHeader.vue
> +              value: 'community-bans',
修正✍

2021-10-15 08:37 UTC, Hiratake approved these changes

2021-10-15 08:37 UTC, Hiratake commented
イイン・ジェーン

2021-10-16 05:34 UTC, book000 commented
👀

2021-10-16 11:43 UTC, book000 commented
(コードオーナーはヒラタケなのでそちらでマージしていただけると助かります)

2021-10-16 11:52 UTC, merged